name: ai_engine
description: "Modular AI engine for on-device processing."
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  tflite_flutter: ^0.10.4
  image: ^4.2.0
  path_provider: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
